In [ ]:
import os
import sys
import time
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

cuda version 9 needed to be installed. with tf-gpu 1.9, keras 2.2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Installing custom Keras Retinanet module

In [ ]:
 %cd "/content/drive/My Drive/Pneumonia/rsna-pneumonia/keras-retinanet"   

/content/drive/My Drive/Pneumonia/rsna-pneumonia/keras-retinanet


In [ ]:
pwd #check current path

'/content/drive/My Drive/Pneumonia/rsna-pneumonia/keras-retinanet'

In [ ]:
!python setup.py build_ext --inplace  #installing keras retinanet

running build_ext
skipping 'keras_retinanet/utils/compute_overlap.c' Cython extension (up-to-date)
copying build/lib.linux-x86_64-3.6/keras_retinanet/utils/compute_overlap.cpython-36m-x86_64-linux-gnu.so -> keras_retinanet/utils


In [ ]:
  #https://drive.google.com/drive/folders/1_ymWr9trBlpkRtKphL6EOxWIn7nNURHl?usp=sharing 

Installing packages of specific versions

In [ ]:
pip install Cython==0.28.5


     |████████████████████████████████| 3.4MB 2.7MB/s 
  Found existing installation: Cython 0.29.20
    Uninstalling Cython-0.29.20:
      Successfully uninstalled Cython-0.29.20


In [ ]:
pip install pydicom==1.1.0

     |████████████████████████████████| 6.7MB 2.8MB/s 


In [ ]:
pip install Keras==2.2.2


     |████████████████████████████████| 307kB 2.5MB/s 
     |████████████████████████████████| 51kB 3.5MB/s 
ERROR: tensorflow 2.2.0 has requirement keras-preprocessing>=1.1.0, but you'll have keras-preprocessing 1.0.2 which is incompatible.
ERROR: tensorflow 2.2.0 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 1.9.0 which is incompatible.
  Found existing installation: Keras-Preprocessing 1.1.2
    Uninstalling Keras-Preprocessing-1.1.2:
      Successfully uninstalled Keras-Preprocessing-1.1.2
  Found existing installation: Keras-Applications 1.0.8
    Uninstalling Keras-Applications-1.0.8:
      Successfully uninstalled Keras-Applications-1.0.8
  Found existing installation: Keras 2.3.1
    Uninstalling Keras-2.3.1:
      Successfully uninstalled Keras-2.3.1


In [ ]:
pip install Keras-Applications==1.0.4


In [ ]:
pip install Keras-Preprocessing==1.0.2


In [ ]:
pip install keras-resnet==0.1.0


  Created wheel for keras-resnet: filename=keras_resnet-0.1.0-py2.py3-none-any.whl size=13346 sha256=de776861da08e1b4b256a97bd1aa6aa79a5b36a1b19c7ac458cf4e10fa1cfec1
  Stored in directory: /root/.cache/pip/wheels/80/dd/ac/842235b63dddac12faa4b48ebe58b8944e8c2e57c2e38dddb6
Successfully built keras-resnet


In [ ]:
pip install tensorflow-gpu==1.9.0 # you will have to restart runtime after installing

     |████████████████████████████████| 229.6MB 59kB/s 
     |████████████████████████████████| 3.3MB 13.3MB/s 
     |████████████████████████████████| 573kB 37.1MB/s 
ERROR: xarray 0.15.1 has requirement setuptools>=41.2, but you'll have setuptools 39.1.0 which is incompatible.
ERROR: tensorflow 2.2.0 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 1.9.0 which is incompatible.
ERROR: google-auth 1.17.2 has requirement setuptools>=40.3.0, but you'll have setuptools 39.1.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
  Found existing installation: tensorboard 2.2.2
    Uninstalling tensorboard-2.2.2:
      Successfully uninstalled tensorboard-2.2.2
  Found existing installation: setuptools 47.3.1
    Uninstalling setuptools-47.3.1:
      Successfully uninstalled setuptools-47.3.1


In [ ]:
#pip install opencv-python==3.4.3.18

     |████████████████████████████████| 25.0MB 1.5MB/s 
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: opencv-python 4.1.2.30
    Uninstalling opencv-python-4.1.2.30:
      Successfully uninstalled opencv-python-4.1.2.30


In [ ]:
pip install h5py==2.8.0


     |████████████████████████████████| 2.8MB 2.6MB/s 
ERROR: tensorflow 2.2.0 has requirement h5py<2.11.0,>=2.10.0, but you'll have h5py 2.8.0 which is incompatible.
ERROR: tensorflow 2.2.0 has requirement keras-preprocessing>=1.1.0, but you'll have keras-preprocessing 1.0.2 which is incompatible.
ERROR: tensorflow 2.2.0 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 1.9.0 which is incompatible.
  Found existing installation: h5py 2.10.0
    Uninstalling h5py-2.10.0:
      Successfully uninstalled h5py-2.10.0


In [ ]:
#Cuda version
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


In [ ]:
#from keras_retinanet.utils.keras_version import check_keras_version

In [ ]:
#check cudnn version
! dpkg -l | grep -i cudnn

hi  libcudnn7                              7.6.5.32-1+cuda10.1                               amd64        cuDNN runtime libraries
ii  libcudnn7-dev                          7.6.5.32-1+cuda10.1                               amd64        cuDNN development libraries and headers


In [ ]:
#downgrade cuda to version 9 from 10
!wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64-deb
!dpkg -i cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64-deb
!apt-key add /var/cuda-repo-9-0-local/7fa2af80.pub
!apt-get update
!apt-get install cuda=9.0.176-1

--2020-07-11 21:10:14--  https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64-deb
Resolving developer.nvidia.com (developer.nvidia.com)... 152.199.0.24
Connecting to developer.nvidia.com (developer.nvidia.com)|152.199.0.24|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.download.nvidia.com/compute/cuda/9.0/secure/Prod/local_installers/cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64.deb?YVNyfpgvtcxtxcfr2HcZvFuet4Fhii-ZAvpaYFN7vqNNAfGKbwxJOMUzMKvvjpJpIu8KxRv0Bhl3BjsCLyqME6N2nq-W4HrZDIw5n-8cgwzithX7T-knrQ03-KajatVyW3gx-a_nAhBtQqeKXGSQLoBsLvmPLL4EZeKgXKRwvfjjpuq5brbpIrwBNUpM_avHglnfgzY2-NCTD17Yh1U4 [following]
--2020-07-11 21:10:15--  https://developer.download.nvidia.com/compute/cuda/9.0/secure/Prod/local_installers/cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64.deb?YVNyfpgvtcxtxcfr2HcZvFuet4Fhii-ZAvpaYFN7vqNNAfGKbwxJOMUzMKvvjpJpIu8KxRv0Bhl3BjsCLyqME6N2nq-W4HrZDIw5n-8cgwzithX7T-kn

In [ ]:
#! sudo apt-cache policy libcudnn7

In [ ]:
#import sys
#sys.path.insert(1, '/content/drive/My Drive/Pneumonia/rsna-pneumonia/')

#import util

In [ ]:
from keras_retinanet import models

In [ ]:
%cd "/content"

/content


In [ ]:
"""Utility functions"""

import os
import sys
import numpy as np
import pydicom
from PIL import Image
import matplotlib.pyplot as plt
import cv2
sys.path.append("keras-retinanet")
from keras_retinanet.utils.image import read_image_bgr, preprocess_image, resize_image


def dicom_to_jpg(in_file, out_file, out_size):
    """ Convert dicom file to jpg with specified size """
    ds = pydicom.read_file(in_file)
    size = (ds.Columns, ds.Rows)
    mode = 'L'
    im = Image.frombuffer(mode, size, ds.pixel_array,
                          "raw", mode, 0, 1).convert("L")
    im = im.resize((out_size, out_size), resample=Image.BICUBIC)
    im.save(out_file, quality=95)


def iou(box1, box2):
    """
    From Yicheng Chen's "Mean Average Precision Metric"
    https://www.kaggle.com/chenyc15/mean-average-precision-metric

    helper function to calculate IoU
    """
    x11, y11, x12, y12 = box1
    x21, y21, x22, y22 = box2
    w1, h1 = x12-x11, y12-y11
    w2, h2 = x22-x21, y22-y21

    area1, area2 = w1 * h1, w2 * h2
    xi1, yi1, xi2, yi2 = max([x11, x21]), max(
        [y11, y21]), min([x12, x22]), min([y12, y22])

    if xi2 <= xi1 or yi2 <= yi1:
        return 0
    else:
        intersect = (xi2-xi1) * (yi2-yi1)
        union = area1 + area2 - intersect
        return intersect / union


def map_iou(boxes_true, boxes_pred, scores, thresholds=[0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75]):
    """
    From Yicheng Chen's "Mean Average Precision Metric"
    https://www.kaggle.com/chenyc15/mean-average-precision-metric

    Mean average precision at differnet intersection over union (IoU) threshold

    input:
        boxes_true: Mx4 numpy array of ground true bounding boxes of one image. 
                    bbox format: (x1, y1, w, h)
        boxes_pred: Nx4 numpy array of predicted bounding boxes of one image. 
                    bbox format: (x1, y1, w, h)
        scores:     length N numpy array of scores associated with predicted bboxes
        thresholds: IoU shresholds to evaluate mean average precision on
    output: 
        map: mean average precision of the image
    """

    # According to the introduction, images with no ground truth bboxes will not be
    # included in the map score unless there is a false positive detection (?)

    # return None if both are empty, don't count the image in final evaluation (?)
    if len(boxes_true) == 0 and len(boxes_pred) == 0:
        return None

    assert boxes_true.shape[1] == 4 or boxes_pred.shape[1] == 4, "boxes should be 2D arrays with shape[1]=4"
    if len(boxes_pred):
        assert len(scores) == len(
            boxes_pred), "boxes_pred and scores should be same length"
        # sort boxes_pred by scores in decreasing order
        boxes_pred = boxes_pred[np.argsort(scores)[::-1], :]

    map_total = 0

    # loop over thresholds
    for t in thresholds:
        matched_bt = set()
        tp, fn = 0, 0
        for i, bt in enumerate(boxes_true):
            matched = False
            for j, bp in enumerate(boxes_pred):
                miou = iou(bt, bp)
                if miou >= t and not matched and j not in matched_bt:
                    matched = True
                    tp += 1  # bt is matched for the first time, count as TP
                    matched_bt.add(j)
            if not matched:
                fn += 1  # bt has no match, count as FN

        # FP is the bp that not matched to any bt
        fp = len(boxes_pred) - len(matched_bt)
        m = tp / (tp + fn + fp)
        map_total += m

    return map_total / len(thresholds)


def get_annotations(generator):
    """ Return list of annotations from generator """
    annotations = []
    for i in range(generator.size()):
        # load the annotations
        annotation = generator.load_annotations(i)[:, :4]
        annotations.append(annotation)
    return annotations


def get_scores(model, image, scale):
    """ Return calculated bounding boxes and scores for an image """
    # run network
    boxes, scores, labels = model.predict_on_batch(
        np.expand_dims(image, axis=0))

    # correct boxes for image scale
    boxes /= scale

    image_scores = scores[0]
    image_boxes = boxes[0]

    return (image_boxes, image_scores)


def get_view_from_dicom(dcmfile):
    """ Return ViewPosition dicom field from .dcm file """
    ds = pydicom.read_file(dcmfile)
    return ds.ViewPosition


def get_views_from_generator(generator, dcmdir):
    views = []
    for i in range(generator.size()):
        dcmfile = os.path.basename(generator.image_path(i))[:-4]+".dcm"
        dcmfpath = os.path.join(dcmdir, dcmfile)
        views.append(get_view_from_dicom(dcmfpath))
    return views


def get_detection_from_file(fpath, model, sz):
    image = read_image_bgr(fpath)
    image = preprocess_image(image)
    image, scale = resize_image(image, min_side=sz)
    return get_scores(model, image, scale)


def get_detections_from_generator(generator, model):
    detections = []

    for i in range(generator.size()):
        path = generator.image_path(i)
        raw_image = generator.load_image(i)
        image = generator.preprocess_image(raw_image.copy())
        image, scale = generator.resize_image(image)
        detections.append(get_scores(model, image, scale))
    return detections


def nms(boxes, scores, overlapThresh):
    """
    adapted from non-maximum suppression by Adrian Rosebrock
    https://www.pyimagesearch.com/2015/02/16/faster-non-maximum-suppression-python/
    """

    # if there are no boxes, return an empty list
    if len(boxes) == 0:
        return np.array([]).reshape(0, 4), np.array([])
    if boxes.dtype.kind == "i":
        boxes = boxes.astype("float")

    pick = []
    x1 = boxes[:, 0]
    y1 = boxes[:, 1]
    x2 = boxes[:, 2]
    y2 = boxes[:, 3]

    # compute the area of the bounding boxes
    area = (x2 - x1 + 1) * (y2 - y1 + 1)

    # sort the bounding boxes by scores in ascending order
    idxs = np.argsort(scores)

    # keep looping while indexes still remain in the indexes list
    while len(idxs) > 0:
        # grab the last index in the indexes list and add the
        # index value to the list of picked indexes
        last = len(idxs) - 1
        i = idxs[last]
        pick.append(i)

        # find the largest (x, y) coordinates for the start of
        # the bounding box and the smallest (x, y) coordinates
        # for the end of the bounding box
        xx1 = np.maximum(x1[i], x1[idxs[:last]])
        yy1 = np.maximum(y1[i], y1[idxs[:last]])
        xx2 = np.minimum(x2[i], x2[idxs[:last]])
        yy2 = np.minimum(y2[i], y2[idxs[:last]])

        # compute the width and height of the bounding box
        w = np.maximum(0, xx2 - xx1 + 1)
        h = np.maximum(0, yy2 - yy1 + 1)

        # compute the ratio of overlap
        overlap = (w * h) / area[idxs[:last]]

        # delete all indexes from the index list that have
        idxs = np.delete(idxs, np.concatenate(([last],
                                               np.where(overlap > overlapThresh)[0])))

    # return only the bounding boxes that were picked using the
    # integer data type
    return boxes[pick], scores[pick]


def wt_av(x, xw, y, yw):
    """ Calculate a weighted average """
    return (x*xw+y*yw)/(xw+yw)


def averages(boxes, scores, overlapThresh, solo_min=0):
    """ Like non-max-suppression, but take weighted averages of overlapping bounding boxes """
    # if there are no boxes, return an empty list
    if len(boxes) == 0:
        return np.array([]).reshape(0, 4), np.array([])
    if boxes.dtype.kind == "i":
        boxes = boxes.astype("float")

    pick = []
    x1 = boxes[:, 0]
    y1 = boxes[:, 1]
    x2 = boxes[:, 2]
    y2 = boxes[:, 3]

    # compute the area of the bounding boxes
    area = (x2 - x1 + 1) * (y2 - y1 + 1)

    # sort the bounding boxes by scores in ascending order
    idxs = np.argsort(scores)

    # keep looping while indexes still remain in the indexes list
    while len(idxs) > 0:
        # grab the last index in the indexes list and add the
        # index value to the list of picked indexes
        last = len(idxs) - 1
        i = idxs[last]

        # find the largest (x, y) coordinates for the start of
        # the bounding box and the smallest (x, y) coordinates
        # for the end of the bounding box
        xx1 = np.maximum(x1[i], x1[idxs[:last]])
        yy1 = np.maximum(y1[i], y1[idxs[:last]])
        xx2 = np.minimum(x2[i], x2[idxs[:last]])
        yy2 = np.minimum(y2[i], y2[idxs[:last]])

        # compute the width and height of the bounding box
        w = np.maximum(0, xx2 - xx1 + 1)
        h = np.maximum(0, yy2 - yy1 + 1)

        # compute the ratio of overlap
        overlap = (w * h) / area[idxs[:last]]

        overlap_idx = np.where(overlap > overlapThresh)[0].tolist()[::-1]

        if len(overlap_idx) == 0:
            if scores[i] >= solo_min:
                pick.append(i)
        else:
            pick.append(i)
            for j in overlap_idx:
                boxes[i, :] = wt_av(boxes[i, :], scores[i],
                                    boxes[idxs[j], :], scores[idxs[j]])
                scores[i] = scores[i]+scores[idxs[j]]

        # delete all indexes from the index list that have
        idxs = np.delete(idxs, np.concatenate(([last],
                                               np.where(overlap > overlapThresh)[0])))

    # return only the bounding boxes that were picked using the
    # integer data type
    if len(pick) > 0:
        return boxes[pick], scores[pick]
    else:
        return np.array([]).reshape(0, 4), np.array([])


def intersects(boxes, scores, overlapThresh, solo_min=0, shrink=0):
    """ Like weighted averages, but take intersections of overlapping bounding boxes """

    # if there are no boxes, return an empty list
    if len(boxes) == 0:
        return np.array([]).reshape(0, 4), np.array([])
    if boxes.dtype.kind == "i":
        boxes = boxes.astype("float")

    pick = []
    x1 = boxes[:, 0]
    y1 = boxes[:, 1]
    x2 = boxes[:, 2]
    y2 = boxes[:, 3]

    # compute the area of the bounding boxes
    area = (x2 - x1 + 1) * (y2 - y1 + 1)

    # sort the bounding boxes by scores in ascending order
    idxs = np.argsort(scores)

    # keep looping while indexes still remain in the indexes list
    while len(idxs) > 0:
        # grab the last index in the indexes list and add the
        # index value to the list of picked indexes
        last = len(idxs) - 1
        i = idxs[last]

        # find the largest (x, y) coordinates for the start of
        # the bounding box and the smallest (x, y) coordinates
        # for the end of the bounding box
        xx1 = np.maximum(x1[i], x1[idxs[:last]])
        yy1 = np.maximum(y1[i], y1[idxs[:last]])
        xx2 = np.minimum(x2[i], x2[idxs[:last]])
        yy2 = np.minimum(y2[i], y2[idxs[:last]])

        # compute the width and height of the bounding box
        w = np.maximum(0, xx2 - xx1 + 1)
        h = np.maximum(0, yy2 - yy1 + 1)

        # compute the ratio of overlap
        overlap = (w * h) / area[idxs[:last]]

        overlap_idx = np.where(overlap > overlapThresh)[0].tolist()[::-1]

        if len(overlap_idx) == 0:
            if scores[i] >= solo_min:
                pick.append(i)

                shrink_factor = shrink/2
                (bx1, by1, bx2, by2) = boxes[i, :]
                diffx = bx2-bx1
                diffy = by2-by1
                boxes[i, 0] += shrink_factor*diffx
                boxes[i, 1] -= shrink_factor*diffx
                boxes[i, 2] += shrink_factor*diffy
                boxes[i, 3] -= shrink_factor*diffy
        else:
            pick.append(i)
            for j in overlap_idx:
                boxes[i, :] = (xx1[j], yy1[j], xx2[j], yy2[j])
                scores[i] = scores[i]+scores[idxs[j]]

        # delete all indexes from the index list that have
        idxs = np.delete(idxs, np.concatenate(([last],
                                               np.where(overlap > overlapThresh)[0])))

    # return only the bounding boxes that were picked using the
    # integer data type
    if len(pick) > 0:
        return boxes[pick], scores[pick]
    else:
        return np.array([]).reshape(0, 4), np.array([])


def shrink(bb, shrink_factor):
    """ Shrinks bounding boxes by a factor in each dimension """
    if len(bb) > 0:
        x1 = bb[:, 0]
        y1 = bb[:, 1]
        x2 = bb[:, 2]
        y2 = bb[:, 3]
        diffx = x2-x1
        diffy = y2-y1
        shrink_factor /= 2
        x1 += shrink_factor*diffx
        x2 -= shrink_factor*diffx
        y1 += shrink_factor*diffy
        y2 -= shrink_factor*diffy


def overlay_box(im, boxx, rgb, stroke):
    """
    Method to overlay single box on image

    """
    # --- Convert coordinates to integers
    for box in boxx:
        box = [int(b) for b in box]
        
        # --- Extract coordinates
        x1, y1, width, height, = box
        y2 = y1 + height
        x2 = x1 + width

        im[y1:y1 + stroke, x1:x2] = rgb
        im[y2:y2 + stroke, x1:x2] = rgb
        im[y1:y2, x1:x1 + stroke] = rgb
        im[y1:y2, x2:x2 + stroke] = rgb

    return im

def draw(im,boxx,path):
    """
    Method to draw single patient with bounding box(es) if present 

    """
    # --- Open DICOM file
    #d = pydicom.read_file(data['dicom'])
    #im = d.pixel_arraymlcour

    # --- Convert from single-channel grayscale to 3-channel RGB
    #im = np.stack([im] * 3, axis=2)

    # --- Add boxes with random color if present

    

    rgb = np.floor(np.random.rand(3) * 256).astype('int')
    im = overlay_box(im=im, boxx=boxx, rgb=rgb, stroke=10)
    im = Image.fromarray(im)

    #changing image saving path for colab environment
    #im.save('./images/'+"checked_"+path)
    im.save('/content/images/'+"checked_"+path)

    #return im.shape

Using TensorFlow backend.


In [ ]:
with open('/content/drive/My Drive/Pneumonia/rsna-pneumonia/settings.json') as json_data_file:
    json_data = json.load(json_data_file)

In [ ]:
model1_path = json_data["MODEL_50"]
#join for colab 
model1_path = os.path.join('/content/drive/My Drive/Pneumonia/rsna-pneumonia/',model1_path )
model1 = models.load_model(model1_path, backbone_name='resnet50', convert=True, nms=False)

In [ ]:
model1_path

'/content/drive/My Drive/Pneumonia/rsna-pneumonia/models/resnet50_csv_22.h5'

In [ ]:
#import tensorflow
#tensorflow.__version__

'1.9.0'

In [ ]:
model2_path = json_data["MODEL_101"]
#join for colab 
model2_path = os.path.join('/content/drive/My Drive/Pneumonia/rsna-pneumonia/',model2_path )
model2 = models.load_model(model2_path, backbone_name='resnet101', convert=True, nms=False)

In [ ]:
sz = 224

# threshold for non-max-suppresion for each model
nms_threshold = 0

# shrink bounding box dimensions by this factor, improves test set performance
shrink_factor = 0.17

# threshold for judging overlap of bounding boxes between different networks (for weighted average)
wt_overlap = 0

# threshold for including boxes from model 1
score_threshold1 = 0.04

# threshold for including boxes from model 2
score_threshold2 = 0.05

# threshold for including isolated boxes from either model
solo_min = 0.15

In [ ]:
import time
import cv2
import os

In [ ]:
pwd

'/content'

In [ ]:
%cd /content

/content


In [ ]:
#create folder to store images
%mkdir images

In [ ]:
file_path=[]
score_list=[]
d = "/content/drive/My Drive/Pneumonia/rsna-pneumonia/data/DR/"
for path in os.listdir(d):
    full_path = os.path.join(d, path)
    if os.path.isfile(full_path):
        file_path.append(path)
        #fid = fname[:-4]
        start = time.time()
        fpath = d+path

        boxes_pred1, scores1 = get_detection_from_file(fpath, model1, sz)
        boxes_pred2, scores2 = get_detection_from_file(fpath, model2, sz)


        indices1 = np.where(scores1 > score_threshold1)[0]
        scores1 = scores1[indices1]
        boxes_pred1 = boxes_pred1[indices1]
        boxes_pred1, scores1 = nms(boxes_pred1, scores1, nms_threshold)

        indices2 = np.where(scores2 > score_threshold2)[0]
        scores2 = scores2[indices2]
        boxes_pred2 = boxes_pred2[indices2]
        boxes_pred2, scores2 = nms(boxes_pred2, scores2, nms_threshold)

        #boxes_pred = boxes_pred1+boxes_pred2
        #scores = scores1+scores2
        
        boxes_pred = np.concatenate((boxes_pred1, boxes_pred2))
        scores = np.concatenate((scores1, scores2))

        boxes_pred, scores = averages(
        boxes_pred, scores, wt_overlap, solo_min)
        shrink(boxes_pred, shrink_factor)
        
        score_list.append(scores)
        
        boxx = []
        #print(boxes_pred,scores)

        for i, bb in enumerate(boxes_pred):
            x1 = int(bb[0])
            y1 = int(bb[1])
            w = int(bb[2]-x1+1)
            h = int(bb[3]-y1+1)

            boxx.append([x1,y1,w,h])

        im = cv2.imread(fpath)
        draw(im,boxx,path)

In [ ]:
print(len(score_list))

140


In [ ]:
score_list

[array([], dtype=float64),
 array([0.44920444, 0.14200695], dtype=float32),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([0.127442], dtype=float32),
 array([], dtype=float64),
 array([0.61687785], dtype=float32),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([0.55684555, 0.28349876], dtype=float32),
 array([], dtype=float64),
 array([], dtype=float64),
 array([0.1930089], dtype=float32),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([0.24927005, 0.24645115], dtype

In [ ]:
data = {'col_1': file_path, 'col_2': score_list}
df=pd.DataFrame.from_dict(data)

In [ ]:
df.to_csv('out.csv')

In [ ]:
pwd

'/content'

In [ ]:
#fid = fname[:-4]
start = time.time()
fpath = '/content/drive/My Drive/Pneumonia/rsna-pneumonia/./test/05.jpg'

#boxes_pred1, scores1 = util.get_detection_from_file(fpath, model1, sz)
boxes_pred2, scores2 = get_detection_from_file(fpath, model2, sz)


# indices1 = np.where(scores1 > score_threshold1)[0]
# scores1 = scores1[indices1]
# boxes_pred1 = boxes_pred1[indices1]
# boxes_pred1, scores1 = util.nms(boxes_pred1, scores1, nms_threshold)

indices2 = np.where(scores2 > score_threshold2)[0]
scores2 = scores2[indices2]
boxes_pred2 = boxes_pred2[indices2]
boxes_pred2, scores2 = nms(boxes_pred2, scores2, nms_threshold)

boxes_pred = boxes_pred2
scores = scores2

boxx = []
#print(boxes_pred,scores)

for i, bb in enumerate(boxes_pred):
    x1 = int(bb[0])
    y1 = int(bb[1])
    w = int(bb[2]-x1+1)
    h = int(bb[3]-y1+1)
    
    boxx.append([x1,y1,w,h])

In [ ]:
import cv2
im = cv2.imread(fpath)

In [ ]:
print(scores)

[0.5625763]


In [ ]:
draw(im,boxx,"cxray.jpg")

In [ ]:
#img = Image.open('/content/images/checked_cxray.jpg')
#img.show()